import pygame
import time

import tkinter.messagebox

white = (255, 255, 255)
red = (255, 0, 0)
running = True

mainWin = pygame.display.set_mode((100, 100))
pygame.display.set_caption("Dad's Day")


mainWin.fill(white)

tkinter.messagebox.showinfo("Dad's Day", "I love you dad!")

while running:
    pygame.draw.rect(mainWin, red, [50, 30, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [60, 20, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [70, 10, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [80, 20, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [90, 30, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [90, 40, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [80, 50, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [70, 60, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [60, 70, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [50, 80, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [40, 80, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [30, 70, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [20, 60, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [10, 50, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [0, 40, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [0, 30, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [10, 20, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [20, 10, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [30, 20, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    pygame.draw.rect(mainWin, red, [40, 30, 10, 10])
    pygame.display.update()
    time.sleep(.25)
    mainWin.fill(white)
    pygame.display.update()
    time.sleep(.25)


pygame.quit()
quit()
